window.fashionItems = [
  {
    id: 'ro-fw26-tower',
    brand: 'RICK OWENS',
    title: 'FW26 TOWER：从仪式感到结构防护',
    summary: '官方产品指南将 TOWER 定位为 2026 秋冬系列；硬挺轮廓、身体防护与灰黑层次继续构成 Owens 的核心语汇。',
    date: '2026-03-05',
    dateLabel: '2026.03.05',
    source: 'Rick Owens · Official',
    sourceType: '官方',
    url: 'https://www.rickowens.eu/en-us/pages/fw26-tower-product-guide-1',
    image: 'https://images.unsplash.com/photo-1539109136881-3be0616acf4b?auto=format&fit=crop&w=1200&q=85',
    tone: 'silver',
    featured: true
  },
  {
    id: 'bal-fall26',
    brand: 'BALENCIAGA',
    title: 'FALL 26：把街头、运动与正式装压进同一层',
    summary: 'Pierpaolo Piccioli 的首个秋冬叙事以“人的手与身体”为轴，落在 TechWear、街头正式装与运动剪裁的并置上。',
    date: '2026-01-15',
    dateLabel: '2026.01.15',
    source: 'Balenciaga · Fall 26',
    sourceType: '官方',
    url: 'https://www.balenciaga.com/en-us/fall-26',
    image: 'https://images.unsplash.com/photo-1551488831-00ddcb6c6bd3?auto=format&fit=crop&w=1200&q=85',
    tone: 'bone',
    featured: true
  },
  {
    id: 'bal-summer26',
    brand: 'BALENCIAGA',
    title: 'SUMMER 26：不是致敬，是重新校准',
    summary: '品牌以“methodology”回到 Cristóbal Balenciaga 的工作方法，把空气、身体和布料之间的张力变成新的夏季轮廓。',
    date: '2025-10-01',
    dateLabel: '2025.10.01',
    source: 'Balenciaga · Summer 26',
    sourceType: '官方',
    url: 'https://www.balenciaga.com/en-gb/summer-26',
    image: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=1200&q=85',
    tone: 'ash',
    featured: false
  },
  {
    id: 'ro-temple-interview',
    brand: 'RICK OWENS',
    title: 'TEMPLE：粗粝与温柔同时存在',
    summary: '在官方访谈中，Owens 将 SS26 的重皮革、流苏和切割细节写成一种“保护身体与灵魂的仪式”。这是设计师原话的编辑化摘要。',
    date: '2025-10-01',
    dateLabel: '2025.10.01',
    source: 'Rick Owens · Interview',
    sourceType: '官方访谈',
    url: 'https://www.rickowens.eu/en-row/blogs/interviews/rick-owens-october-2025',
    image: 'https://images.unsplash.com/photo-1538805060514-97d9cc17730c?auto=format&fit=crop&w=1200&q=85',
    tone: 'coal',
    featured: false
  },
  {
    id: 'ro-ss26-runway',
    brand: 'RICK OWENS',
    title: 'SS26 TEMPLE：走进水里，走出另一种秀场',
    summary: 'Vogue 的秀场记录捕捉到黑色隐形眼镜、Lucite 平台鞋与水中行进的强烈场面；这里标注为媒体观察，不与品牌声明混同。',
    date: '2025-10-02',
    dateLabel: '2025.10.02',
    source: 'Vogue Runway',
    sourceType: '媒体观察',
    url: 'https://www.vogue.com/fashion-shows/spring-2026-ready-to-wear/rick-owens',
    image: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=1200&q=85',
    tone: 'ink',
    featured: false
  },
  {
    id: 'ro-runway-archive',
    brand: 'RICK OWENS',
    title: 'RUNWAY ARCHIVE：TEMPLE 与 TOWER 已进入官方档案',
    summary: '官方 Runway Shows 页面把 SS26 TEMPLE、FW26 TOWER 与更早系列并列归档，形成一条可回溯的黑色谱系。',
    date: '2025-09-30',
    dateLabel: '2025.09.30',
    source: 'Rick Owens · Runway Shows',
    sourceType: '官方档案',
    url: 'https://www.rickowens.eu/en-lux/pages/runway-shows',
    image: 'https://images.unsplash.com/photo-1485230895905-ec40ba36b9bc?auto=format&fit=crop&w=1200&q=85',
    tone: 'graphite',
    featured: false
  },
  {
    id: 'adjacent-signal',
    brand: 'ADJACENT SIGNAL',
    title: '相邻信号：当运动功能变成新的正式语法',
    summary: '从 Balenciaga Fall 26 的 TechWear 与运动正装并置，到 Owens 的身体护甲式比例，两个方向正在共享“可穿着的防御性”。',
    date: '2025-09-29',
    dateLabel: '2025.09.29',
    source: '编辑部交叉阅读',
    sourceType: '编辑判断',
    url: 'https://www.balenciaga.com/en-us/fall-26',
    image: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=1200&q=85',
    tone: 'steel',
    featured: false
  }
];
